IF NOT EXISTS(SELECT 1 FROM sys.tables WHERE name LIKE '%SchemaMigrations')
BEGIN
CREATE TABLE [dbo].[SchemaMigrations](
	[SchemaMigrationNumber] [varchar](255) NOT NULL,
 CONSTRAINT [PK_SchemaMigrations] PRIMARY KEY CLUSTERED 
(
	[SchemaMigrationNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
END